### ISSUE TITLE
deploy.sh does not export CFN_CAPABILITY on dockerhub's bitovi/bitops:latest

### ISSUE THREAD

**Issue by rwubafs** [bitops-plugins/cloudformation#4]
Hi, the image I pulled today from bitovi/bitops:latest on dockerhub had an issue with the cloudformation plugin.. 
The image SHA256 hash is c3d2856c08c2573cee7b0cb1b54334f22e95815b1d80608741ef0f63caf030d4.

In deploy.sh I had to add an export line for the variable ```CFN_CAPABILITY``` otherwise my attempted run would silently fail trying to create a cloudformation stack.

I may have had something misconfigured, but hope this is useful :).

**Comment by arm4b** [comment]
Thanks, @rwubafs for reporting this 👍 
Sounds like a bug!

We'll take a closer look at that.

**Comment by PhillypHenning** [comment]
Very useful information, thank you
So to me the issue here is a lack of proper reporting around Cloudformation, specifically on failure. 
I believe this plugin is missing a piece of reporting for when a Cloudformation stack fails. 

Reporting happens when the status is `completed_successfully` as we expect so I think it's just that the error is falling between the cracks so to speak and not properly being reported in the logs. 

Quick fix suggestion;
[This line](https://github.com/bitops-plugins/cloudformation/blob/2e69609fa1542e09df9a0423127fc0d941ef0267/scripts/cloudformation_deploy.sh#L106) needs to be updated to watch for any status, not just a successful one

**Comment by rwubafs** [comment]
I did notice that without adding an export line in the top level deploy.sh, the cloudformation_deploy.sh got an empty string for the CFN_CAPABILITY, and I assume that was making the aws command croak early, but not 100% sure

**Comment by arm4b** [comment]
@rwubafs I see now, `BITOPS_CFN_CAPABILITY` is not passed anywhere to the script here: https://github.com/bitops-plugins/cloudformation/blob/main/deploy.sh#L13-L25 and so `CFN_CAPABILITY` is empty here https://github.com/bitops-plugins/cloudformation/blob/main/deploy.sh#L102.

@rwubafs Good catch! Motivated to create a quick PR?

**Comment by rwubafs** [comment]
https://github.com/bitops-plugins/cloudformation/pull/5

**Comment by mickmcgrath13** [comment]
Linking for reference based on @PhillypHenning 's comment above:
https://github.com/bitops-plugins/cloudformation/issues/4
